name: dependabot automerge

on:
  pull_request:
    types:
      - opened
      - reopened
permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/dependabot-automerge.yml@v0
