name: eslint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: "npm"

      - name: npm ci
        run: |
          npm ci
        env:
          CI: true

      - name: npm run lint
        run: |
          npm run lint
