name: hadolint
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "Dockefile"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
