name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push HEAD to main version branch
        run: |
          major_version=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9]+)\..+/\1/")
          git push --force origin "HEAD:refs/heads/${major_version}"
          minor_version=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9]+\.[0-9]+).+/\1/")
          git push --force origin "HEAD:refs/heads/${minor_version}"
