name: Run Tagging and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

permissions: {}

jobs:
  call:
    permissions:
      contents: write
    uses: chick-p/github-actions-shared-workflow/.github/workflows/release.yml@2f12e0eb5d446e4f36a1247417445beda6ac474e # v0.4.1
    with:
      version: ${{ inputs.version }}
