name: Run Tagging and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/release.yml@19278e10d4e7f1860a5ff184e9ddc622bba230f3 # v0.4.0
    with:
      version: ${{ inputs.version }}
