name: Run Tagging and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
